export default [
  {
    path: '/duiwujianshe/user',
    layout: false,
    routes: [
      {name: '登录', path: '/duiwujianshe/user/login', component: './user/Login'},
      // { component: './404' },
    ],
  },
  {path: '/duiwujianshe/welcome', component: './duiwujianshe_welcome'},
  // {
  //   // path: '/duiwujianshe/admin',
  //   name: '队伍举报投诉管理',
  //   icon: 'table',
  //   // access: 'canAdmin',
  //   routes: [
  //     {name: '举报投诉分发', icon: 'table', path: '/duiwujianshe/duiwujianshejbtsgl', component: './duiwujianshejbtsgl', access:'zhuanban'},
  //     {name: '举报投诉分发', icon: 'table', path: '/duiwujianshe/duiwujianshejbtsglguanli', component: './duiwujianshejbtsglguanli', access:'zhuanbanandguanli'},
  //     {name: '单位自查', icon: 'table', path: '/duiwujianshe/duiwujianshedwbmhcdanwei', component: './duiwujianshedwbmhcdanwei',},
  //     {name: '警种复核', icon: 'table', path: '/duiwujianshe/duiwujianshedwbmhcjingzhong', component: './duiwujianshedwbmhcjingzhong',},
  //     {name: '整改落实', icon: 'table', path: '/duiwujianshe/duiwujianshezgls', component: './duiwujianshezgls',},
  //     {name: '举报投诉归档', icon: 'table', path: '/duiwujianshe/duiwujianshejbtsgd', component: './duiwujianshejbtsgd',},
  //     {name: '问题归档', icon: 'table', path: '/duiwujianshe/duiwujianshewtgd', component: './duiwujianshewtgd', access:'canAdmin'},
  //     {name: '日常督导管理', icon: 'table', path: '/duiwujianshe/duiwujianshercddgl', component: './duiwujianshercddgl',access:'canAdmin'},
  //     {name: '问题处置', icon: 'table', path: '/duiwujianshe/duiwujianshewtcz', component: './duiwujianshewtcz',access:'canAdmin'},
  //   ],
  // },
  // {
  //   // path: '/duiwujianshe/admin',duiwujianshewtcz
  //   name: '日常督导检查管理',
  //   icon: 'table',
  //   // access: 'canAdmin',
  //   routes: [
  //     {name: '日常督导管理', icon: 'table', path: '/duiwujianshe/duiwujianshercddgl', component: './duiwujianshercddgl',},
  //     {name: '问题处置', icon: 'table', path: '/duiwujianshe/duiwujianshewtcz', component: './duiwujianshewtcz',},
  //     {name: '问题归档', icon: 'table', path: '/duiwujianshe/duiwujianshewtgd', component: './duiwujianshewtgd',},
  //   ],
  // },
  // {name: '事件录入', icon: 'table', path: '/duiwujianshe/Tablelist', component: './Tablelist', access:'luruandshenpiandguanli',},

  {name: '事件录入', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianluru100', component: './duiwujianshe_shijianluru111', access:'luru',},
  {name: '事件录入', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianluru110', component: './duiwujianshe_shijianluru111', access:'luruandshenpi',},
  {name: '事件录入', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianluru101', component: './duiwujianshe_shijianluru111', access:'luruandguanli',},
  {name: '事件录入', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianluru111', component: './duiwujianshe_shijianluru111', access:'luruandshenpiandguanli',},
  {name: '事件审批', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianshenpi010', component: './duiwujianshe_shijianshenpi111', access:'shenpi',},
  {name: '事件审批', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianshenpi110', component: './duiwujianshe_shijianshenpi111', access:'luruandshenpi',},
  {name: '事件审批', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianshenpi011', component: './duiwujianshe_shijianshenpi111', access:'shenpiandguanli',},
  {name: '事件审批', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianshenpi111', component: './duiwujianshe_shijianshenpi111', access:'luruandshenpiandguanli',},
  {name: '专管视图', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianchakanzhuanguan', component: './duiwujianshe_shijianchakanzhuanguan',access: 'zhuanban'},
  {name: '事件视图', icon: 'table', path: '/duiwujianshe/duiwujianshe_shijianchakan', component: './duiwujianshe_shijianchakan'},
  {name: '人员视图', icon: 'table', path: '/duiwujianshe/duiwujianshe_renyuanshitu010', component: './duiwujianshe_renyuanshitu111', access:'shenpi',},
  {name: '人员视图', icon: 'table', path: '/duiwujianshe/duiwujianshe_renyuanshitu110', component: './duiwujianshe_renyuanshitu111', access:'luruandshenpi',},
  {name: '人员视图', icon: 'table', path: '/duiwujianshe/duiwujianshe_renyuanshitu011', component: './duiwujianshe_renyuanshitu111', access:'shenpiandguanli',},
  {name: '人员视图', icon: 'table', path: '/duiwujianshe/duiwujianshe_renyuanshitu111', component: './duiwujianshe_renyuanshitu111', access:'luruandshenpiandguanli',},
  {name: '个人中心', icon: 'form', path: '/duiwujianshe/duiwujianshe_gerenzhongxin', component: './duiwujianshe_gerenzhongxin',},
  {name: '账号管理', icon: 'table', path: '/duiwujianshe/duiwujianshe_zhanghaoguanli001', component: './duiwujianshe_zhanghaoguanli111', access:'guanli'},
  {name: '账号管理', icon: 'table', path: '/duiwujianshe/duiwujianshe_zhanghaoguanli101', component: './duiwujianshe_zhanghaoguanli111', access:'luruandguanli'},
  {name: '账号管理', icon: 'table', path: '/duiwujianshe/duiwujianshe_zhanghaoguanli011', component: './duiwujianshe_zhanghaoguanli111', access:'shenpiandguanli'},
  {name: '账号管理', icon: 'table', path: '/duiwujianshe/duiwujianshe_zhanghaoguanli111', component: './duiwujianshe_zhanghaoguanli111', access:'luruandshenpiandguanli'},

  // { name: '机柜管理', icon: 'table', path: '/wuziguanli/jiguiguanlilist', component: './Jiguiguanlilist' },
  // { name: '设备管理', icon: 'table', path: '/wuziguanli/shebeiguanlilist', component: './Shebeiguanlilist' },
  // { name: '测试', icon: 'table', path: '/wuziguanli/test', component: './Test' },

  // { name: '一机一档查看', icon: 'table', path: '/yijiyidang/yijiyidangadmin', component: './yijiyidangadmin',access: 'canAdmin',  },
  // { name: '一机一档查看', icon: 'table', path: '/yijiyidang/yijiyidangyys', component: './yijiyidangyys',access: 'canYys',  },
  // { name: '一机一档查看', icon: 'table', path: '/yijiyidang/yijiyidangpcs', component: './yijiyidangpcs',access: 'canPcs',  },
  // { name: '一机一档查看', icon: 'table', path: '/yijiyidang/yijiyidangkjk', component: './yijiyidangkjk',access: 'canKjk',  },
  // { name: '一机一档审批', icon: 'table', path: '/yijiyidang/yijiyidangshenpiadmin', component: './yijiyidangshenpiadmin',access: 'canAdmin', },
  // { name: '一机一档确认', icon: 'table', path: '/yijiyidang/yijiyidangquerenadmin', component: './yijiyidangquerenadmin',access: 'canAdmin', },
  // { name: '一机一档审批', icon: 'table', path: '/yijiyidang/yijiyidangshenpi', component: './yijiyidangshenpi',access: 'canPcs', },
  // { name: '一机一档确认', icon: 'table', path: '/yijiyidang/yijiyidangqueren', component: './yijiyidangqueren',access: 'canKjk', },
    //
    // { name: '设备修改申请', icon: 'table', path: '/yijiyidang/yijiyidangsbxgsq', component: './yijiyidangsbxgsq',access: 'canAdmin',   },
    // { name: '设备修改申请', icon: 'table', path: '/yijiyidang/yijiyidangsbxgsqyys', component: './yijiyidangsbxgsqyys', access: 'canYys', },
    // { name: '设备修改审批', icon: 'table', path: '/yijiyidang/yijiyidangsbxgsp', component: './yijiyidangsbxgsp', access: 'canAdmin',  },
    // { name: '设备修改审批', icon: 'table', path: '/yijiyidang/yijiyidangsbxgspspz', component: './yijiyidangsbxgspspz', access: 'canSpz', },
    // { name: '设备历史查看', icon: 'table', path: '/yijiyidang/yijiyidangsblishichakan', component: './yijiyidangsblishichakan', access: 'canAdmin',  },
    // { name: '设备历史查看', icon: 'table', path: '/yijiyidang/yijiyidangsblishichakanspz', component: './yijiyidangsblishichakanspz', access: 'canSpz', },

  // { path: '/', redirect: '/yijiyidang/yijiyidang',access: 'canYys', },
  // { path: '/', redirect: '/yijiyidang/yijiyidangshenpi',access: 'canPcs', },
  // { path: '/', redirect: '/yijiyidang/yijiyidangqueren',access: 'canKjk', },

  // {name: '举报投诉分发', icon: 'table', path: '/duiwujianshe/duiwujianshejbtsgl', component: './duiwujianshejbtsgl',},
  // {name: '单位部门核查', icon: 'table', path: '/duiwujianshe/duiwujianshedwbmhc', component: './duiwujianshedwbmhc',},
  // {name: '整改落实', icon: 'table', path: '/duiwujianshe/duiwujianshezgls', component: './duiwujianshezgls',},
  // {name: '举报投诉归档', icon: 'table', path: '/duiwujianshe/duiwujianshejbtsgd', component: './duiwujianshejbtsgd',},
  // { path: '/', redirect: '/wuziguanli/shebeiguanlilist' },
  // { component: './404' },
];
